version: '1.0'
services:
  axonserver:
    image: axoniq/axonserver:latest
    hostname: axonserver
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-log:/axonserver/log
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      - AXONIQ_AXONSERVER_STANDALONE=true

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-log: